### PR TITLE
Remove usage of let

### PR DESCRIPTION
**Pull request by bmathews**

### CODE REVIEW

**Review by Holger-Will — APPROVED** [review]
nice find. thanks!

**Comment by bmathews** [comment]
No problem! Should I expect a release of this in the near future, or should I point my package.json to use my fork for now?

**Comment by Holger-Will** [comment]
just merged and published 0.2.0 (i know it should have just been a patch...)

**Comment by bmathews** [comment]
Thanks you! And thanks for the great library!

**Pull request merged**
